### ISSUE TITLE
Settings schema isn't properly installed

### ISSUE THREAD

**Issue by danirabbit** [bartzaalberg/bookmark-manager#13]
https://github.com/bartzaalberg/bookmark-manager/blob/072eafa38e9c465e0c10cb276ee4954f397c592d/CMakeLists.txt#L70

It looks like your settings schema doesn't get installed properly, causing your app to crash on run. Instead of manually copying, you should do something like [this](https://github.com/elementary/appcenter/blob/master/schemas/CMakeLists.txt)

**Comment by unbelievableflavour** [comment]
Updated the code, hope this should work.
https://github.com/bartzaalberg/bookmark-manager/commit/0677dc078f40902f9fea55fdb5096a45d034c958
