### ISSUE TITLE
Displaying the list with more complicated ssh config entries

### ISSUE THREAD

**Issue by kmf** [bartzaalberg/bookmark-manager#16]
I have about a 160 entries in my ssh config, some of entries look like this 
```
  Host piglet
    HostName 10.0.0.20
    ForwardAgent yes
    User kmf
    ProxyCommand ssh pooh nc %h %p
```
Could you add support for that?

**Comment by unbelievableflavour** [comment]
Hi! Atm I'm a bit sick. But I will try that later! Sure

Op 8 sep. 2017 12:00 schreef Karl Fischer <notifications@github.com>:

I have about a 160 entries in my ssh config, some of entries look like this

  Host piglet
    HostName 10.0.0.20
    ForwardAgent yes
    User kmf
    ProxyCommand ssh pooh nc %h %p


Could you add support for that?

**Comment by unbelievableflavour** [comment]
Release 1.2.0(which is now in cert) is running just by name. So it should load all your configurations from your file. This should probably fix your problem. Also i added agent Forwarding and proxyCommands to the edit and add forms.
