### ISSUE TITLE
SSH name?

### ISSUE THREAD

**Issue by peteruithoven** [bartzaalberg/bookmark-manager#17]
I'm glad to see this app making managing ssh config easier, but I'm having some issues getting started. 
It starts with asking what my SSH name is, but I have no idea what this is? Is this the username of my computer? I don't remember having to set a SSH name before. 

Also, when I try to fill this in, the window only has a Close button and pressing enter doesn't seem to do anything? 
![screenshot from 2017-09-10 22 11 22](https://user-images.githubusercontent.com/523210/30252558-034980ac-9675-11e7-8bbf-ecf614a20c0a.png)

**Comment by unbelievableflavour** [comment]
Hi, sorry for the confusion. This is the default ssh username which is used when your ssh config doesn't contain one. I will make it more clear in my next release!

Op 10 sep. 2017 22:13 schreef Peter Uithoven <notifications@github.com>:

I'm glad to see this app making managing ssh config easier, but I'm having some issues getting started.
It starts with asking what my SSH name is, but I have no idea what this is? Is this the username of my computer? I don't remember having to set a SSH name before.

Also, when I try to fill this in, the window only has a Close button and pressing enter doesn't seem to do anything?
[screenshot from 2017-09-10 22 11 22]<https://user-images.githubusercontent.com/523210/30252558-034980ac-9675-11e7-8bbf-ecf614a20c0a.png>

**Comment by unbelievableflavour** [comment]
Made the preferences window a bit more clear in version 1.1.6 which is now in testing. If you have any suggestions on making it better. Please let me know.

**Comment by peteruithoven** [comment]
Thanks for the clear answer. It's much clearer in the latest release, thanks! 
I was also confused by the list being empty, but that has also been fixed in the mean time.

**Comment by unbelievableflavour** [comment]
no problem!
