### ISSUE TITLE
[Question]: How can I add a new config item?

### ISSUE THREAD

**Issue by artemanufrij** [bartzaalberg/bookmark-manager#20]
I see just an empty window and I don't know how to add a new config item....

![bildschirmfoto von 2017-09-16 12 05 31](https://user-images.githubusercontent.com/16517095/30511371-05022f9c-9ac7-11e7-8459-e16aedc33490.png)

**Comment by unbelievableflavour** [comment]
For now you have to add them manually to the ~/.ssh/config file.you can look it up on Google. But in the next update, there will be an add and delete function. I'm almost done, there is just one little building error which I will fix today.

Op 16 sep. 2017 12:08 schreef Artem Anufrij <notifications@github.com>:

I see just an empty window and I don't know how to add a new config item....

[bildschirmfoto von 2017-09-16 12 05 31]<https://user-images.githubusercontent.com/16517095/30511371-05022f9c-9ac7-11e7-8459-e16aedc33490.png>

**Comment by artemanufrij** [comment]
Thank you for your response!
