### ISSUE TITLE
Just a quick typo error

### ISSUE THREAD

**Issue by yeboahnanaosei** [bartzaalberg/bookmark-manager#22]
Check the highlighted word.

![ssh_manager](https://user-images.githubusercontent.com/22800157/30516283-0ec22ee8-9b2a-11e7-8a11-01ff771d0015.png)

**Comment by unbelievableflavour** [comment]
Ah thanks. I'll change that. I'f you find more of those. Please let me know!

Op 16 sep. 2017 23:58 schreef Nana Yeboah <notifications@github.com>:

Check the highlighted word.

[ssh_manager]<https://user-images.githubusercontent.com/22800157/30516283-0ec22ee8-9b2a-11e7-8a11-01ff771d0015.png>
