### ISSUE TITLE
broken 'ProxyCommand' after reload a config

### ISSUE THREAD

**Issue by artemanufrij** [bartzaalberg/bookmark-manager#23]
1. Create a ssh bookmark
2. Add a `ProxyCommand`
3. Save it
4. Edit saved bookmark:

Spaces between command elements are missing.

![bildschirmfoto von 2017-09-17 10 06 55](https://user-images.githubusercontent.com/16517095/30519227-9a9ac932-9b90-11e7-91ad-5a25f59991cc.png)

**Comment by unbelievableflavour** [comment]
Is fixed in this release.
