### ISSUE TITLE
Buttons too close to each other

### ISSUE THREAD

**Issue by ayoisaiah** [bartzaalberg/bookmark-manager#24]
Currently the buttons touch each other, some padding is needed.

![com github bartzaalberg bookmark-manager_043](https://user-images.githubusercontent.com/13372163/30571058-07021a74-9cdd-11e7-8c22-bb7f2e25708f.png)

![selection_045](https://user-images.githubusercontent.com/13372163/30571102-6ee1a89e-9cdd-11e7-9356-0bfcb092219f.png)

**Comment by unbelievableflavour** [comment]
Added it to the master. Will be in the next release.
