### ISSUE TITLE
Store password

### ISSUE THREAD

**Issue by luizamorimsouza** [bartzaalberg/bookmark-manager#27]
The app could save the password

**Comment by bartzaalberg** [comment]
passwords for ssh?

**Comment by unbelievableflavour** [comment]
The app is not a password manager. It is merely a gui for ssh.

**Comment by luizamorimsouza** [comment]
okay, but it would be great functionality primarily for people who manages multiple servers. It is unfeasible to prune the password of all the servers and annoying to search in some file.

**Comment by unbelievableflavour** [comment]
I use multiple servers. But i login with ssh which doesn't ask me for the password at all and is alot safer. So i can't test this for you. But feel free to create a pull request yourself! I will help wherever i can.
