### ISSUE TITLE
Local and RemoteForwards

### ISSUE THREAD

**Issue by kmaks-dev** [bartzaalberg/bookmark-manager#28]
I often use LocalForward and RemoteForward to tunnel some key connections via ssh.

There is no support for this ssh feature and if i have multiple such forwards set bookmark-manager removes all but last from my config!

Since I run some ssh connections purely for those forwards I'd suggest also adding a "hide-window" feature alongside such forwards.

**Comment by unbelievableflavour** [comment]
Will look into this.

**Comment by unbelievableflavour** [comment]
Could you be a bit more clear about when this is happening? Because for me, only the one i'm actually editing removes loalForward and RemoteForward. The rest stays the same for me.

**Comment by unbelievableflavour** [comment]
Which i now fixed in master

**Comment by unbelievableflavour** [comment]
@ovdeathiam Can you tell me if you're still experiencing this please?

**Comment by unbelievableflavour** [comment]
No comments. I will close this.
