### ISSUE TITLE
Add jumplist with bookmarks in dock

### ISSUE THREAD

**Issue by Extravert-ir** [bartzaalberg/bookmark-manager#29]
It would be great to add a short list of most used (or maybe last used) bookmarks right in dock to be able to launch them without app open

**Comment by unbelievableflavour** [comment]
That would be awesome yeah! will definitly try this.

**Comment by unbelievableflavour** [comment]
Apparently this is not that easily created. If i would do this i would have to create a cron which would constantly overwrite the .desktop file from the application which is in a root directory. A simple solution could be made using polkit but this would mean i would have to enter my password every time i would open bookmark manager. And that is not an option. It should be possible to create another simple application which does this while running in the background. But i don't have the time to create that.

**Comment by unbelievableflavour** [comment]
Oh actually it was a lot easier then i thought. I'm almost done. Now to hope it gets approved :P

**Comment by Extravert-ir** [comment]
Seems like Plank supports LauncherEntry API from Unity. Maybe you should try it
[https://wiki.ubuntu.com/Unity/LauncherAPI](https://wiki.ubuntu.com/Unity/LauncherAPI)

**Comment by unbelievableflavour** [comment]
Yes, but the way i did it, it will also show up in slingshot. Does this also work with the launcherEntry api? Because i thought i read somewhere that didn't work. But this does looks like a nicer solution.

**Comment by Extravert-ir** [comment]
I couldn't determine the api support by just glancing at slingshot's source code(
What do you mean exactly by showing up in slingshot?

**Comment by unbelievableflavour** [comment]
When pressing 'applications' in the upper left corner of your screen. Slingshot will open. Here you will find all your applications. But when searching. You can also search for application actions. In my current code. Here all my bookmarks will show up. I don't know it that is also happening for  the unity launcher entry api.

**Comment by unbelievableflavour** [comment]
This is in current release. Can this ticket be closed?

**Comment by Extravert-ir** [comment]
Sorry, had too much work recently.
I've updated the app (two times already) and seems like bookmarks feature does not work on my system. I click "Update bookmarks", enter my password and nothing happens: still have only two items in jumplist, "Keep in Dock" and "About Bookmark Manager"
