### ISSUE TITLE
Nickname for the servers

### ISSUE THREAD

**Issue by rvbd** [bartzaalberg/bookmark-manager#31]
Sometimes the host that I'm connecting to is a direct IP. It would be great if I can give a nickname to the bookmark. That way it'll be even easier to identify which server is which.

This is a good start though, one of the easiest one to use out there.

**Comment by unbelievableflavour** [comment]
Thank you! Glad you like it. But could you explain it a little more? Because if you wan't to give your ip's some names. You could just fill in the 'Host' as nickname right? Or am i misunderstanding you.

**Comment by rvbd** [comment]
Hello. So if I put the host as the nickname, for example: test-server-1. Then the ssh command executed was ssh user@test-server-1 when in reality it's only a nickname and not a DNS record. 

That's why I thought it'll be great if we can have some sort of free text nickname for each entries.
![screenshot from 2017-10-24 20 51 06](https://user-images.githubusercontent.com/1558550/31936362-18186f98-b8fd-11e7-9207-d1278db6de33.jpeg)

**Comment by unbelievableflavour** [comment]
Oh like that. That's something i can do;)

**Comment by rvbd** [comment]
Awesomeness!

**Comment by unbelievableflavour** [comment]
Added this to master. Whenever a nickname is filled in. It should show the nickname instead of the hostname. The nickname is saved in the host as comment.

**Comment by unbelievableflavour** [comment]
Added it to release 1.3.2
