### ISSUE TITLE
Welcome screen should provide access to app functions immediately

### ISSUE THREAD

**Issue by worldofpeace** [bartzaalberg/bookmark-manager#32]
When you first start the app it says:
![image](https://user-images.githubusercontent.com/28888242/32141352-82538c62-bc54-11e7-9fad-5f45a39c3b64.png)

This is counter intuitive to the HIG of elementary OS :(
Don't take my word for it. Here's the [docs](https://github.com/elementary/website/blob/master/docs/human-interface-guidelines.md#avoid-configuration-avoid-configuration)

**Comment by unbelievableflavour** [comment]
Removed it. Is in release 1.3.3

**Comment by worldofpeace** [comment]
@bartzaalberg
Thank you for getting to fixing this so quickly! 

But I noticed now that you removed the welcome screen that on first run, or when you have no bookmarks that there's just a blank view now.
![image](https://user-images.githubusercontent.com/28888242/32170775-5ace31bc-bd4c-11e7-8946-5d55dd600661.png)
But if you click the add bookmark button and press back we get to this view.
![image](https://user-images.githubusercontent.com/28888242/32170836-9bdbb864-bd4c-11e7-857c-2838121323fe.png)
This should be the welcome screen.

**Comment by unbelievableflavour** [comment]
oh, i overlooked that. I will fix that in a couple of minutes.

**Comment by unbelievableflavour** [comment]
Could you check master if it is now correct?

**Comment by worldofpeace** [comment]
Everything works as expected!

**Comment by unbelievableflavour** [comment]
thanks!
