### ISSUE TITLE
GtkSeachEntry, (search bookmarks) should not be visable on EmptyView

### ISSUE THREAD

**Issue by worldofpeace** [bartzaalberg/bookmark-manager#33]
Why would you seach for bookmarks when you have none?
It should appear after you make one.

Not to mention it looks really weird when you try to search. :)
![peek 2017-10-30 11-42](https://user-images.githubusercontent.com/28888242/32180155-93707a3c-bd67-11e7-88ca-2c445e58578d.gif)

**Comment by unbelievableflavour** [comment]
Good point. will fix that

**Comment by worldofpeace** [comment]
I've seen **many** other elementary OS applications do similar things like this for instance with buttons also.(making them not clickable or visable yet, etc.) That might be something also to do with any other app you make.

**Comment by unbelievableflavour** [comment]
Yes, i'm trying that. But for some weird reason i'm running into the problem that my headerBar won't update. Still trying to fix that.

**Comment by worldofpeace** [comment]
You can try to code Frankenstien this project [Spice-Up](https://github.com/Philip-Scott/Spice-up).
:)

**Comment by unbelievableflavour** [comment]
I have no idea what that means xp

**Comment by worldofpeace** [comment]
I just made it up. There's the functionality in this app that you want so you can try to look in his code and sorta replicate it? Hence the, assembling a living being from parts of exhumed corpses.

**Comment by unbelievableflavour** [comment]
Hahahah. Ok

**Comment by unbelievableflavour** [comment]
The problem is not that i cannot make it hidden or insensitive. The problem is that i have to reuse 1 headerBar for the whole project. And as soon as i call it 2 times. it doesn't update the first.(obviously). So i create an instance. But when i create an instance i get a segmentation fault. Which gives me no feedback whats however.

**Comment by worldofpeace** [comment]
I see. Can you make a branch in git and upload the code?
> But when i create an instance i get a segmentation fault. Which gives me no feedback whats 
> however.

I hate when vala does that!
I feel you.

**Comment by unbelievableflavour** [comment]
Pushed. Its called dynamic-searchbar

**Comment by worldofpeace** [comment]
Perfect name. :)

**Comment by unbelievableflavour** [comment]
Its seems to be caused by listbox, which is called by bookmarkListManager. If i remove bookmarkListManager from headerBar. It works.But i need bookmarkListManager :P

**Comment by unbelievableflavour** [comment]
I removed the listManager and made an instance of the listbox. This makes it a bit easier to read.

**Comment by worldofpeace** [comment]
Haha. I just realized that I would have made more sense for you to open a pull request on yourself and have me review it. :)

> I removed the listManager and made an instance of the listbox.

Good call.

**Comment by Philip-Scott** [comment]
Hey @bartzaalberg!

What you can probably do is have a singleton for your headerbar class so only one will be created :) From there, you'll be able to get the instance of it and call it's methods.

So when you want to modify it's properties, you can do:

```vala
MyHeaderBar.get_instance ().sensitive = false;
```

See https://github.com/Philip-Scott/Notes-up/blob/master/src/Widgets/Headerbar.vala#L46 for an example on how a singleton works :)

**Comment by unbelievableflavour** [comment]
Hi @Philip-Scott . Thanks for the tip! But that's already in my branch. Problem is that when i call my singleton multiple times. I get a segmentation fault.

**Comment by unbelievableflavour** [comment]
YESSS. Finally fixed it. It's in the release 1.3.5.
Please test this and close the issue when it's tested OK.

**Comment by worldofpeace** [comment]
I found one thing.
![peek 2017-11-10 13-08](https://user-images.githubusercontent.com/28888242/32672495-45b8bc86-c619-11e7-8ec6-143b495a9630.gif)

**Comment by unbelievableflavour** [comment]
Fixed in master

**Comment by worldofpeace** [comment]
LGTM :+1: :1st_place_medal:
