### ISSUE TITLE
Use AppStream Release info?

### ISSUE THREAD

**Issue by peteruithoven** [bartzaalberg/bookmark-manager#34]
The changes per release are currently very readably documented [per release on github](https://github.com/bartzaalberg/bookmark-manager/releases), thank you for that. Since a few updates the AppCenter can now show release info per update, could you maybe also add it so it can be shown there? 

https://github.com/elementary/appcenter/issues/24
https://bugs.launchpad.net/appcenter/+bug/1612810/comments/2

**Comment by peteruithoven** [comment]
Adam Bieńkowski: 
> All metadata is contained usually within the `data/*.appdata.xml` file, in this case, here: https://github.com/bartzaalberg/bookmark-manager/blob/master/data/com.github.bartzaalberg.bookmark-manager.appdata.xml

**Comment by unbelievableflavour** [comment]
Ah, so thats why that doesn't work. I was putting it in the debian/changelog file. Will move over the changelog to the appdata.xml file when i have some spare time today ;)

**Comment by unbelievableflavour** [comment]
Added it. It is now in master

**Comment by peteruithoven** [comment]
Thanks!
