### ISSUE TITLE
The description of the "start an SSH session" button

### ISSUE THREAD

**Issue by robertsanseries** [bartzaalberg/bookmark-manager#35]
The description of the "start an SSH session" button does not make it very clear that it will be started in the terminal.

<strike>Have you ever considered having the terminal in your application?<strike>

**Comment by unbelievableflavour** [comment]
Any suggestions?

And i have considered that. But i have no idea how to create that.

**Comment by unbelievableflavour** [comment]
changed it to this "Start an SSH session in a terminal" for now. Is in master

**Comment by worldofpeace** [comment]
>Have you ever considered having the terminal in your application?
>
This would broaden the use of this app instead of just being an ssh config manager and more of an ssh client.

There is an app that is sorta like this called [Termius](https://www.termius.com/).
This is a good idea. Just no practical implementation currently. :)

**Comment by robertsanseries** [comment]
@bartzaalberg 

This class is only responsible for creating a terminal (<strike>you can customize the colors to your liking.</strike>)
https://github.com/robertsanseries/snow/blob/master/src/widgets/Terminal.vala

Example of use
```vala
 var box = new Gtk.Box (Gtk.Orientation.HORIZONTAL, 0);
height_request = 130;

var terminal = new Terminal ();
terminal.expand = true;
        	
var scrolled = new Gtk.ScrolledWindow (null, null);
scrolled.add (terminal);

box.add (scrolled);
```

https://valadoc.org/vte-2.91/Vte.Terminal

**Comment by unbelievableflavour** [comment]
Will check that out.. If it's something i will add it as an optional toggle in the preferences menu.

**Comment by unbelievableflavour** [comment]
Btw.... Snow looks  awesome. Why isn't it in the app center?

**Comment by robertsanseries** [comment]
@bartzaalberg LoL coming soon!

**Comment by unbelievableflavour** [comment]
Nice. Looking forward to that!

**Comment by unbelievableflavour** [comment]
@robertsanseries i'm created a branch where i added the Vte terminal. But now i want to send the ssh command to the Vte terminal. And this is kind off a pain in the ass. Could you maybe take a look. Or explain what i should call?

**Comment by unbelievableflavour** [comment]
Never mind. Got it

**Comment by worldofpeace** [comment]
Yay! Terminal in the app. :1st_place_medal: 

I'm thinking that this should be the default way of doing things btw.
Design choices shouldn't be a setting ever.

Can't wait to see what you do with this. :)

**Comment by unbelievableflavour** [comment]
It's not really a design choice. Some people just prefer using the Elementary terminal instead of the one i am creating :P

**Comment by robertsanseries** [comment]
@bartzaalberg eave the option for the user to decide!

**Comment by unbelievableflavour** [comment]
It's already a toggle in settings now. Still figuring out how to output errors in the Vte. When that's done i will merge it to master.

**Comment by worldofpeace** [comment]
The terminal in the app should be restricted to only appearing when you establish a ssh connection.
You click on the start button and then the terminal appears in some manner within the app. This makes the workflow more concise and apparent. :mag:

**Comment by unbelievableflavour** [comment]
Ok, this is all in the submitted release. If there are any more things about the terminal. Make a separate ticket because we got way off ticket.
