### ISSUE TITLE
Add support for translation

### ISSUE THREAD

**Issue by robertsanseries** [bartzaalberg/bookmark-manager#36]
I would like to translate your app into Portuguese from Brazil!

Note: Also add string translation to the AppCenter.

**Comment by unbelievableflavour** [comment]
I have no idea how to test this.
But i created a branch which i followed all translation instructions in.
Is this what you where looking for?
https://github.com/bartzaalberg/bookmark-manager/tree/add-multilanguage-support

**Comment by unbelievableflavour** [comment]
And how do i add string translation to appcenter?

**Comment by robertsanseries** [comment]
> I have no idea how to test this.

Create a file with translation in another language, and then change to translated language in the system settings of the elementary.

> But i created a branch which i followed all translation instructions in.
Is this what you where looking for?

Yes =D

**Comment by robertsanseries** [comment]
> And how do i add string translation to appcenter?

You can follow this examples: 

[Gnome Music] (https://github.com/GNOME/gnome-music)
[Gnome Calendar] (https://github.com/GNOME/gnome-calendar)
[Gnome Maps] (https://github.com/GNOME/gnome-maps)
[Gnome Photos] (https://github.com/GNOME/gnome-photos)

<hr>
1º - Change the names of the files:

From:
`com.github.bartzaalberg.bookmark-manager.desktop`
`com.github.bartzaalberg.bookmark-manager.appdata.xml`

To:
`com.github.bartzaalberg.bookmark-manager.desktop.in`
`com.github.bartzaalberg.bookmark-manager.appdata.xml.in`

<hr>
2º - Convert these files via makefile (<strike>for the makefile reads the strings</strike>)

Example:


https://github.com/GNOME/gnome-calculator/blob/master/data/Makefile.am)

```am
desktopdir = $(datadir)/applications
desktop_in_files = org.gnome.Calculator.desktop.in
desktop_DATA = $(desktop_in_files:.desktop.in=.desktop)

$(desktop_DATA): $(desktop_in_files)
	$(AM_V_GEN) $(MSGFMT) --desktop --template $< -d $(top_srcdir)/po -o $@


appstream_in_files = org.gnome.Calculator.appdata.xml.in
appstream_XML = $(appstream_in_files:.xml.in=.xml)

$(appstream_XML): $(appstream_in_files)
	$(AM_V_GEN) $(MSGFMT) --xml --template $< -d $(top_srcdir)/po -o $@
```

<hr>
3º - In PO's add the strings of files: 

`com.github.bartzaalberg.bookmark-manager.desktop.in` 
`com.github.bartzaalberg.bookmark-manager.appdata.xml.in`  

That will be converted.

Exemple:

https://github.com/GNOME/gnome-music/blob/master/po/pt_BR.po

```po
#: ../data/gnome-music.desktop.in.h:2
msgid "Music Player"
msgstr "Reprodutor de músicas"

#: ../data/gnome-music.appdata.xml.in.h:3
msgid "Music is the new GNOME music playing application."
msgstr "O Música é o novo aplicativo reprodutor de música do GNOME."
```

**Comment by unbelievableflavour** [comment]
Ok so the translating stuff is now in master. Also added a Dutch translation to test with. All working correctly so thats cool. String translating for App Center still needs to be done. Which i'm trying now. But the new translation strings won't show up in the .pot file. Which is probably because elementary vala apps don't use Makefile.am. And when i'm trying to put that in CmakeList.txt i get errors.

**Comment by unbelievableflavour** [comment]
And how the hell can i test this without doing a release? 0.o

**Comment by robertsanseries** [comment]
@bartzaalberg I believe that only generating a version! :-1:

**Comment by unbelievableflavour** [comment]
@robertsanseries Ah ok. And is it correct that i manually have to add the language strings? Because for the application strings the get generated in the pot file. This does't happen for the appcenter strings.

**Comment by robertsanseries** [comment]
@bartzaalberg Yes, you can check this in elementary applications, and in the Nimbus or Ciano app.

**Comment by unbelievableflavour** [comment]
Unfortunately those applications use meson so can't use that. Any other examples which i can look at? Because my build keeps giving errors.

**Comment by robertsanseries** [comment]
@bartzaalberg I can see your problem only on the 20th!

**Comment by unbelievableflavour** [comment]
That's not a problem. Thank you!

**Comment by unbelievableflavour** [comment]
Soo..... did you take a look at it?

**Comment by NathanBnm** [comment]
@bartzaalberg maybe you have to close this issue now

**Comment by unbelievableflavour** [comment]
I will. Thnx!
https://github.com/bartzaalberg/bookmark-manager/issues/48
