### ISSUE TITLE
Problem launching shh connections via elementary terminal 

### ISSUE THREAD

**Issue by jos-henson** [bartzaalberg/bookmark-manager#37]
Hi there,

I use the elementary os daily ppa, so have the newer version of the Terminal app that has been renamed using the new elementary os project 'style' system for built-in apps, which means bookmark-manager fails to launch the terminal to run ssh connections.

The issue is on line 94 of the DesktopFileManager.vala source file I believe, which has the following:

actionString += "Exec=pantheon-terminal --execute='ssh " + username + "@" + bookmark.getName() + "'\n";

To work successfully once the new terminal app and name change lands in the elementary os stable repository, this would need to be switched to:

actionString += "Exec=io.elementary.terminal --execute='ssh " + username + "@" + bookmark.getName() + "'\n";

Obviously though, hardcoding this change would break the app for people that have not updated, or who have uninstalled the default elementary terminal app because they prefer an alternative terminal app (e.g. gnome-terminal, terminex etc)

Therefore, would it be possible to have the error dialogue that displays when bookmark-manager fails to find pantheon-terminal provide an option to choose an alternative terminal app to run ssh with. Or, perhaps provide this as a 'hidden' option in dconf, so as not to complicated the Preferences window in the app while still providing the option to use a different terminal app for users with non-default installations.

Many thanks for your hard work on this great app!

**UPDATE**

Sorry, there is also one other reference to pantheon-terminal that would need to be changed in ListRowBox.vala on line 83.

Again though, while this works fine for me when I build from source, if possible having the terminal client not hard-coded would perhaps be a good idea to 'future-proof' it and allow even cross-distro usage. Just my humble opinion though, sorry if it sounds critical!! :-)

**Comment by unbelievableflavour** [comment]
How about a field in the preferences where you can set the name of your terminal? Would that be enough?

**Comment by unbelievableflavour** [comment]
Added to master. Will be in next release.

**Comment by jos-henson** [comment]
Hi there, thanks for reviewing this and agreeing to add a new feature for the next release!

As I said in my original post, if you want to keep the Preferences simple, which is in line with elementary OS HIG, then I think a 'hidden' setting accessible via dconf would be more than enough.

The reason is that I don't think this is an option the majority of users will actually need/want to change as they will use the default Terminal app (and when the new io.elementary.terminal name changes in the stable repository this issue will go away, since it was just because I use the daily PPA right now)

If you did want to make it a 'visible' option in the preferences, my personal recommendation would be to make it as a simple as possible rather than requiring users to know or try and locate the command for their Terminal app of choice (e.g. gnome-terminal etc) 

Therefore, is it possible to use something similar to the 'Open with' dialogue you would see in Pantheon Files, as while I am not a programmer I have a feeling this might be some sort of easy to copy/integrate API/GTK widget etc (again, I'm not a programmer, so this may be completely wrong, but hopefully you get what I mean anyway and there is some similar mechanism that would be easy to implement)

Thanks again for your great work on this app!
