### ISSUE TITLE
Starting terminal blocks main app

### ISSUE THREAD

**Issue by artemanufrij** [bartzaalberg/bookmark-manager#39]
If you start a terminal from main app it will blocked by new process

**Comment by unbelievableflavour** [comment]
Could you please explain the problem a little better?

**Comment by artemanufrij** [comment]
@bartzaalberg 
1. open the app
2. add a new ssh connection
3. open connection (2)
-> main app is blocked... You can't focus it until you close terminal (3)

**Comment by sefeiba** [comment]
I have same issue, and when I close the terminal I get:


(io.elementary.terminal:10565): Gtk-CRITICAL **: 11:11:07.642: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(io.elementary.terminal:10565): Gtk-CRITICAL **: 11:11:07.662: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

**Comment by markmorris** [comment]
@sefeiba Having the same issue.

**Comment by unbelievableflavour** [comment]
I think I fixed it. Check latest release if the problem still occurs.

**Comment by unbelievableflavour** [comment]
It's been released. Please check if the problem still occurs. @artemanufrij
