### ISSUE TITLE
Title bar is blue!

### ISSUE THREAD

**Issue by markmorris** [bartzaalberg/bookmark-manager#40]
App looks odd compare to every other app, why a bigger title bar and why blue? I use this daily but looks horrible. Doesnt fit with the rest of OS.

**Comment by unbelievableflavour** [comment]
Sorry, i haven't been on Elementary for some time now. As for my job i must use a mac. 
If you think its that horrible, you could always create a PR ;)

**Comment by markmorris** [comment]
Thanks for the fast reply, sorry i may have been a bit blunt, i love this app, works perfect, this is the first time is use ElementaryOS on Loki. Just looked well odd compared to other apps. If i have time i will update and make a PR. Thanks

**Comment by unbelievableflavour** [comment]
Yeah Elementary OS is lovely. If u wouldnt have to use Mac it would be my main OS again. Buy which colour would you choose? Default Grey? Because alle my apps have a different color bar. And i thought that was actually what was in the elementary designs. But i could be wrong.

**Comment by unbelievableflavour** [comment]
This issue is 3 months old and is not really an issue, if you want another color for the title bar you will have to create a PR. Closing this.

**Comment by markmorris** [comment]
I understand that its not a bug, sorry about posting this, but here is my Elementary OS in 2018.

I opened as many windows as i could, all different apps. Can you see the issue here, that's why i thought it was a bug, it was just different. I will close this post.

![screenshot from 2018-10-16 10-07-24](https://user-images.githubusercontent.com/7857906/47005379-8762d400-d12b-11e8-8a7b-3936d8092a9c.png)

**Comment by unbelievableflavour** [comment]
Those are almost all Elementary OS system apps. As my app Snaptastic with an Orange theme even got linked in their own blog. I think its fine. https://medium.com/elementaryos/developer-tips-branding-your-app-a57cb44d31d3
