### ISSUE TITLE
Change requested for AppCenter: install GSettings to correct path

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/bookmark-manager#45]
Your GSettings are being installed to `/org/example/my-app/`, which does not match your app's RDNN.

https://github.com/bartzaalberg/bookmark-manager/blob/d2282c9e8288d2709b12ef475c960660c391c11a/data/com.github.bartzaalberg.bookmark-manager.gschema.xml#L2

**Comment by unbelievableflavour** [comment]
Oh, that's probably wrong in all my apps then. Will have look tonight.

**Comment by unbelievableflavour** [comment]
@cassidyjames I changed it in master. Is only changing the path enough? Or do i need to change more than that?

**Comment by cassidyjames** [comment]
@bartzaalberg changing the path should be good as long as everything compiles and works as expected. :smile:

**Comment by unbelievableflavour** [comment]
It does. Can i close the issue then? I want to release :)

**Comment by cassidyjames** [comment]
@bartzaalberg go for it!
