### ISSUE TITLE
.desktop file location changed

### ISSUE THREAD

**Issue by greenmanspirit** [bartzaalberg/bookmark-manager#50]
Hello,

When trying to run com.github.bartzaalberg.bookmark-manager-quicklist-polkit, the following error occurs
```
There was an error in the spawned process: 
** (com.github.bartzaalberg.bookmark-manager-quicklist:17302): ERROR **: 10:08:19.052: DesktopFileManager.vala:29: Error opening file ?/usr/local/share/applications/com.github.bartzaalberg.bookmark-manager.desktop?: No such file or directory
```

When I looked on my system, the .desktop file is located at /usr/share/applications/com.github.bartzaalberg.bookmark-manager.desktop.

I am on a fully patched Juno system.

**Comment by unbelievableflavour** [comment]
Thnx, must have changed since Juno. I added the fix to master. It will be in the next release.

**Comment by greenmanspirit** [comment]
Just installed the new version, it worked perfectly.

**Comment by greenmanspirit** [comment]
Thank you for an awesome app.

**Comment by unbelievableflavour** [comment]
Thnx! Closing this issue.
