### ISSUE TITLE
export connections

### ISSUE THREAD

**Issue by abedinia** [bartzaalberg/bookmark-manager#54]
Hello, I would like to export all my ssh connections from the app. I have not seen any button for exporting the connections. 
ElementryOS is my installed distribution. I will be happy if anyone reply :)

**Comment by kissmybackend** [comment]
It will be realy useful feature.

**Comment by unbelievableflavour** [comment]
It would yet, though this project is not actively maintained anymore. If you are willing to make a pull request I would be happy to merge it and create a release for you.

**Comment by greenmanspirit** [comment]
I can look into this. Since this app is a graphical front end for ~/.ssh/config, are you thinking to export in that format to move to another system with an ssh config file or is there a another app you all would like to import into?

**Comment by unbelievableflavour** [comment]
Gotta wonder though. Since it's just a graphical front end for ~/.ssh/config.. Isn't the "~/.ssh/config" file just always and exported version of the connections?

**Comment by greenmanspirit** [comment]
That's what I was thinking but I wasn't sure if @abedinia or @kissmybackend had another app they wanted to import into that needed a different format.

**Comment by abedinia** [comment]
it has been resolved with the config file. thanks 👍
